Adds PrintJson to bluemix/terminal/table
IBM-Cloud/ibm-cloud-cli-sdk pull request #298
Opened 2022-02-02 23:46 UTC by allmightyspiff

I use this table library a lot in the `ibmcloud sl` plugin, and it would be nice to have a way to simply print the table as a JSON string. Currently my only option is to print the raw data that went into the table originally, which might not match up exactly with what I want to show the user.

My approach here was to just render the table as an array, each row being an object with each property matching a column in the table.

For example
```go
	testTable := NewTable(&buf, []string{"test1", "test2"})
	testTable.Add("row1-col1", "row1-col2")
	testTable.Add("row2-col1", "row2-col2")
	testTable.PrintJson()
```
would render something like this:

```json
[
        {
                "test1": "row1-col1",
                "test2": "row1-col2"
        },
        {
                "test1": "row2-col1",
                "test2": "row2-col2"
        }
]
```

2022-02-03 19:53 UTC, jorge-ibm requested changes
Thanks for adding this functionality @allmightyspiff! Looks like there's some gosec failures that need to be addressed.

2022-02-03 19:53 UTC, jorge-ibm commented on bluemix/terminal/table_test.go
> +func TestPrintTableSimple(t *testing.T) {
Thanks for adding these tests. Though I want to ask if you can maybe add some negative tests? What happens if the headers are empty strings ? Just want to make sure this new functionality is robust.

2022-02-03 20:04 UTC, allmightyspiff commented
@jorge-ibm the gosec errors seems to be in unrelated files.  Although since both errors look like they are supposed to create a file from a variable, these might be false positives? 

I'll also add some more tests as well, so no worries there.

```
$  gosec -exclude-dir=plugin_examples -exclude-dir=vendor -quiet ./...
Results:


[ibm-cloud-cli-sdk\common\file_helpers\gzip.go:67] - G304 (CWE-22): Potential file inclusion via variable (Confidence: HIGH, Severity: MEDIUM)
    66:
  > 67:                 f, err := os.Create(path)
    68:                 if err != nil {



[ibm-cloud-cli-sdk\common\file_helpers\file.go:55] - G304 (CWE-22): Potential file inclusion via variable (Confidence: HIGH, Severity: MEDIUM)
    54:
  > 55:         destFile, err := os.Create(dest)
    56:         if err != nil {
```

2022-02-03 20:56 UTC, jorge-ibm commented
thanks @allmightyspiff. I'll need to take a look at the gosec failures then. Also I just noticed, but can you please re-open this PR against the `dev` branch ?

2022-02-03 22:07 UTC, allmightyspiff commented
Ok, I've rebased to `dev`, added more unit tests checking a few more "non-optimal" table setups and marked the 2 gosec violations as false positives.

my interpretation of the G304 error is that it only really applies if the go process has higher privileges than the user supplying the input, which I don't think is the case for the cli.

2022-02-04 15:59 UTC, jorge-ibm approved these changes

2022-02-04 15:59 UTC, jorge-ibm commented on common/file_helpers/file.go
> +	//#nosec G304 -- This is a false positive
I think this should be fine given we clean the path prior.

2022-02-04 18:55 UTC, boyang9527 approved these changes

2022-02-04 19:07 UTC, merged